$(function(){
    $('.profil').click(function(){
        $('.profil2').css('visibility', 'visible').click(function(){
          $('.presentation').html("<h1>NEDJADI Ahmed</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce finibus volutpat finibus. Mauris euismod nulla congue mattis posuere. Etiam metus eros, imperdiet ut magna at, scelerisque consequat mauris. Donec lobortis posuere pretium. Morbi a massa eu urna accumsan venenatis quis in metus. Praesent eget convallis lacus. Cras in cursus eros. Aenean tincidunt mi nec nisi tincidunt, vitae egestas nunc vehicula. Nullam ut elit et diam pharetra dictum nec et tortor. Curabitur leo lacus, pretium eu tincidunt quis, finibus ut purus. Pellentesque id justo sapien. Donec molestie enim orci, nec varius lectus porttitor ut. Aliquam egestas consequat mauris, nec interdum dolor sodales vel.</p> <a href=\"http://agent-simplon.github.io/cvAhmed.html\"<div class=\"btn-cv\">Voir le CV</div></a>")
        });
        $('.profil3').css('visibility', 'visible').click(function(){
          $('.presentation').html("<h1>BOUALI Abdel-Malik</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce finibus volutpat finibus. Mauris euismod nulla congue mattis posuere. Etiam metus eros, imperdiet ut magna at, scelerisque consequat mauris. Donec lobortis posuere pretium. Morbi a massa eu urna accumsan venenatis quis in metus. Praesent eget convallis lacus. Cras in cursus eros. Aenean tincidunt mi nec nisi tincidunt, vitae egestas nunc vehicula. Nullam ut elit et diam pharetra dictum nec et tortor. Curabitur leo lacus, pretium eu tincidunt quis, finibus ut purus. Pellentesque id justo sapien. Donec molestie enim orci, nec varius lectus porttitor ut. Aliquam egestas consequat mauris, nec interdum dolor sodales vel.</p> <a href=\"http://agent-simplon.github.io/cvbouali.html\"<div class=\"btn-cv\">Voir le CV</div></a>")
        });
        $('.profil3-bis').css('visibility', 'visible').click(function(){
          $('.presentation').html("<h1>FANNIO Jérome</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce finibus volutpat finibus. Mauris euismod nulla congue mattis posuere. Etiam metus eros, imperdiet ut magna at, scelerisque consequat mauris. Donec lobortis posuere pretium. Morbi a massa eu urna accumsan venenatis quis in metus. Praesent eget convallis lacus. Cras in cursus eros. Aenean tincidunt mi nec nisi tincidunt, vitae egestas nunc vehicula. Nullam ut elit et diam pharetra dictum nec et tortor. Curabitur leo lacus, pretium eu tincidunt quis, finibus ut purus. Pellentesque id justo sapien. Donec molestie enim orci, nec varius lectus porttitor ut. Aliquam egestas consequat mauris, nec interdum dolor sodales vel.</p> <a href=\"http://agent-simplon.github.io/cv2.html\"<div class=\"btn-cv\">Voir le CV</div></a>")
        });
        $('.profil4').css('visibility', 'visible').click(function(){
          $('.presentation').html("<h1>M'CHINDRA Adel-Ben</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce finibus volutpat finibus. Mauris euismod nulla congue mattis posuere. Etiam metus eros, imperdiet ut magna at, scelerisque consequat mauris. Donec lobortis posuere pretium. Morbi a massa eu urna accumsan venenatis quis in metus. Praesent eget convallis lacus. Cras in cursus eros. Aenean tincidunt mi nec nisi tincidunt, vitae egestas nunc vehicula. Nullam ut elit et diam pharetra dictum nec et tortor. Curabitur leo lacus, pretium eu tincidunt quis, finibus ut purus. Pellentesque id justo sapien. Donec molestie enim orci, nec varius lectus porttitor ut. Aliquam egestas consequat mauris, nec interdum dolor sodales vel.</p> <a href=\"http://agent-simplon.github.io/cvslyz.html\"<div class=\"btn-cv\">Voir le CV</div></a>")
        });
        $('.profil5').css('visibility', 'visible').click(function(){
          $('.presentation').html("<h1>SERY Nadege</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce finibus volutpat finibus. Mauris euismod nulla congue mattis posuere. Etiam metus eros, imperdiet ut magna at, scelerisque consequat mauris. Donec lobortis posuere pretium. Morbi a massa eu urna accumsan venenatis quis in metus. Praesent eget convallis lacus. Cras in cursus eros. Aenean tincidunt mi nec nisi tincidunt, vitae egestas nunc vehicula. Nullam ut elit et diam pharetra dictum nec et tortor. Curabitur leo lacus, pretium eu tincidunt quis, finibus ut purus. Pellentesque id justo sapien. Donec molestie enim orci, nec varius lectus porttitor ut. Aliquam egestas consequat mauris, nec interdum dolor sodales vel.</p> <a href=\"http://agent-simplon.github.io/cvnadege.html\"<div class=\"btn-cv\">Voir le CV</div></a>")
        });
        });
    });
